
define write_objs
$(eval do=$(wordlist 1, ${1}, ${2}))\
$(if $(word 1, $(do)),\
	$(eval last=$(subst $(do),,${2}))\
	$(info $(strip ${3}) $(do))\
	$(shell ${3} $(do) >> ${4})\
	$(call write_objs, ${1}, $(last), ${3}, ${4}),$(info ***** $(strip ${3}) finished *****))
endef


define obj2file
$(shell echo.exe "" > ${2})\
$(call write_objs, 100, ${1}, echo.exe, ${2})
endef
