/**
 * @file
 * Ethernet Interface Skeleton
 *
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/*
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

#include "lwip/opt.h"

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include "lwip/stats.h"
#include "lwip/snmp.h"
#include "lwip/ethip6.h"
#include "lwip/etharp.h"
#include "netif/ppp/pppoe.h"

// 包含头文件
#include <wifi_netif.h>
#include "wifi.h" // 为了保证可移植性, 这个文件中定义的内容应该与lwip协议栈和STM32单片机完全无关

#if LWIP_IPV6

// Wi-Fi模块无硬件校验功能, 所以不能在lwip里面启用硬件校验
#if !LWIP_CHECKSUM_CTRL_PER_NETIF
#if !CHECKSUM_GEN_IP || !CHECKSUM_GEN_UDP || !CHECKSUM_GEN_TCP || !CHECKSUM_GEN_ICMP || !CHECKSUM_GEN_ICMP6
#error "Checksum cannot be generated by Wi-Fi module hardware!"
#endif
#endif

/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'

/* Forward declarations. */
#if LWIP_IPV6 && LWIP_IPV6_MLD
static err_t ethernetif_mld_mac_filter(struct netif *netif, const ip6_addr_t *group, enum netif_mac_filter_action action);
#endif

/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static void
low_level_init(struct netif *netif)
{
  /* set MAC hardware address length */
  netif->hwaddr_len = ETHARP_HWADDR_LEN;

  /* maximum transfer unit */
  netif->mtu = 1500;

  /* device capabilities */
  /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
  netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP; // 网卡默认状态为: 未连接

#if LWIP_IPV6 && LWIP_IPV6_MLD
  netif->flags |= NETIF_FLAG_MLD6; // 必须要启用这个选项, 才能ping通IPv6地址
  netif_set_mld_mac_filter(netif, ethernetif_mld_mac_filter);
  
  /*
   * For hardware/netifs that implement MAC filtering.
   * All-nodes link-local is handled by default, so we must let the hardware know
   * to allow multicast packets in.
   * Should set mld_mac_filter previously. */
  if (netif->mld_mac_filter != NULL) {
    ip6_addr_t ip6_allnodes_ll;
    ip6_addr_set_allnodes_linklocal(&ip6_allnodes_ll);
    netif->mld_mac_filter(netif, &ip6_allnodes_ll, NETIF_ADD_MAC_FILTER);
  }
#endif /* LWIP_IPV6 && LWIP_IPV6_MLD */

  /* Do whatever else is needed to initialize interface. */
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become available since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */

static err_t
low_level_output(struct netif *netif, struct pbuf *p)
{
  struct ethernetif *ethernetif = netif->state;
  
  port_t port = -1; // -1表示发送失败
  WiFi_DataTx *packet;

#if ETH_PAD_SIZE
  pbuf_remove_header(p, ETH_PAD_SIZE); /* drop the padding word */
#endif
  
  packet = WiFi_GetPacketBuffer(p->tot_len); // 获取发送缓冲区
  if (packet != NULL)
  {
    pbuf_copy_partial(p, packet->payload, p->tot_len, 0); // 把要发送的数据帧复制到发送缓冲区中
    if (netif_is_link_up(netif))
    {
      WiFi_SetPacketHeader(packet, ethernetif->bss, p->tot_len);
      port = WiFi_SendPacket(packet); // 发送数据帧
    }
  }
  
#if WIFI_DISPLAY_PACKET_SIZE
  printf("[Send] len=%d, bss=0x%02x, port=%d\n", p->tot_len, ethernetif->bss, port);
#else
  LWIP_UNUSED_ARG(port);
#endif
  
  if (packet != NULL)
  {
#if WIFI_DISPLAY_PACKET_TX
    WiFi_LowLevel_Dump(packet->payload, p->tot_len);
#endif
    WiFi_ReleasePacketBuffer(); // 释放发送缓冲区
  }

  MIB2_STATS_NETIF_ADD(netif, ifoutoctets, p->tot_len);
  if (((u8_t *)p->payload)[0] & 1) {
    /* broadcast or multicast packet*/
    MIB2_STATS_NETIF_INC(netif, ifoutnucastpkts);
  } else {
    /* unicast packet */
    MIB2_STATS_NETIF_INC(netif, ifoutucastpkts);
  }
  /* increase ifoutdiscards or ifouterrors on error */

#if ETH_PAD_SIZE
  pbuf_add_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

  LINK_STATS_INC(link.xmit);

  return ERR_OK;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
static struct pbuf *
low_level_input(struct netif *netif)
{
  struct ethernetif *ethernetif = netif->state;
  struct pbuf *p;
  u16_t len;
  
  const WiFi_DataRx *data = ethernetif->data;
  int ret;

  /* Obtain the size of the packet and put it into the "len"
     variable. */
  len = data->rx_packet_length;
#if WIFI_DISPLAY_PACKET_SIZE
  printf("[Recv] len=%d, bss=0x%02x, port=%d", len, ethernetif->bss, ethernetif->port);
#if WIFI_DISPLAY_PACKET_RXRATES
  printf(", SNR=%ddB, NF=-%ddBm, priority=%d", (int)data->snr, data->nf, data->priority);
  if (data->rx_rate != 0)
  {
    printf(", rates: ");
    WiFi_PrintRates(data->rx_rate);
  }
#endif
  printf("\n");
#endif
#if WIFI_DISPLAY_PACKET_RX
  WiFi_LowLevel_Dump(data->payload, len);
#endif
  
  // 在WMM开启的情况下, 无法打开固件自带的Intra-BSS forwarding功能 (由MrvlIETypes_PKT_Fwd_Ctrl_t控制)
  // 所以必须自己转发uAP热点客户端之间的数据包, 无法由固件自动转发
  ret = WiFi_ForwardPacket(data, netif->hwaddr);
#if WIFI_DISPLAY_PACKET_SIZE
  if (ret != 0)
    printf("[Forward] len=%d, bss=0x%02x, port=%d\n", len, ethernetif->bss, ret);
#else
  LWIP_UNUSED_ARG(ret);
#endif

#if ETH_PAD_SIZE
  len += ETH_PAD_SIZE; /* allow room for Ethernet padding */
#endif

  /* We allocate a pbuf chain of pbufs from the pool. */
  p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);

  if (p != NULL) {

#if ETH_PAD_SIZE
    pbuf_remove_header(p, ETH_PAD_SIZE); /* drop the padding word */
#endif

    pbuf_take(p, data->payload, data->rx_packet_length); // 将数据帧内容复制到pbuf中

    MIB2_STATS_NETIF_ADD(netif, ifinoctets, p->tot_len);
    if (((u8_t *)p->payload)[0] & 1) {
      /* broadcast or multicast packet*/
      MIB2_STATS_NETIF_INC(netif, ifinnucastpkts);
    } else {
      /* unicast packet*/
      MIB2_STATS_NETIF_INC(netif, ifinucastpkts);
    }
#if ETH_PAD_SIZE
    pbuf_add_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

    LINK_STATS_INC(link.recv);
  } else {
    LINK_STATS_INC(link.memerr);
    LINK_STATS_INC(link.drop);
    MIB2_STATS_NETIF_INC(netif, ifindiscards);
  }

  return p;
}

/**
 * This function should be called when a packet is ready to be read
 * from the interface. It uses the function low_level_input() that
 * should handle the actual reception of bytes from the network
 * interface. Then the type of the received packet is determined and
 * the appropriate input function is called.
 *
 * @param netif the lwip network interface structure for this ethernetif
 */
void
ethernetif_input(struct netif *netif)
{
  struct pbuf *p;

  /* move received packet into a new pbuf */
  p = low_level_input(netif);
  /* if no packet could be read, silently ignore this */
  if (p != NULL) {
    /* pass all packets to ethernet_input, which decides what packets it supports */
    if (netif->input(p, netif) != ERR_OK) {
      LWIP_DEBUGF(NETIF_DEBUG, ("ethernetif_input: IP input error\n"));
      pbuf_free(p);
      p = NULL;
    }
  }
}

/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t
ethernetif_init(struct netif *netif)
{
  struct ethernetif *ethernetif;

  LWIP_ASSERT("netif != NULL", (netif != NULL));

  ethernetif = mem_malloc(sizeof(struct ethernetif));
  if (ethernetif == NULL) {
    LWIP_DEBUGF(NETIF_DEBUG, ("ethernetif_init: out of memory\n"));
    return ERR_MEM;
  }
  
  // 把BSS号码保存到netif->state中
  LWIP_ASSERT("netif->state != NULL", netif->state != NULL);
  ethernetif->bss = *(bss_t *)netif->state;

#if LWIP_NETIF_HOSTNAME
  /* Initialize interface hostname */
  netif->hostname = "STM32F407VE_SDIO"; // 路由器中显示的名称
#endif /* LWIP_NETIF_HOSTNAME */

  /*
   * Initialize the snmp variables and counters inside the struct netif.
   * The last argument should be replaced with your link speed, in units
   * of bits per second.
   */
  MIB2_INIT_NETIF(netif, snmp_ifType_ethernet_csmacd, LINK_SPEED_OF_YOUR_NETIF_IN_BPS);

  netif->state = ethernetif;
  netif->name[0] = IFNAME0;
  netif->name[1] = IFNAME1;
  /* We directly use etharp_output() here to save a function call.
   * You can instead declare your own function an call etharp_output()
   * from it if you have to do some checks before sending (e.g. if link
   * is available...) */
#if LWIP_IPV4
  netif->output = etharp_output;
#endif /* LWIP_IPV4 */
#if LWIP_IPV6
  netif->output_ip6 = ethip6_output;
#endif /* LWIP_IPV6 */
  netif->linkoutput = low_level_output;

  ethernetif->ethaddr = (struct eth_addr *) & (netif->hwaddr[0]);

  /* initialize the hardware */
  low_level_init(netif);

  return ERR_OK;
}

#if LWIP_IPV6 && LWIP_IPV6_MLD
// IPv6必须要有多播才能正常工作
static err_t ethernetif_mld_mac_filter(struct netif *netif, const ip6_addr_t *group, enum netif_mac_filter_action action)
{
  int ret;
  struct ethernetif *ethernetif = netif->state;
  uint8_t addr[WIFI_MACADDR_LEN] = {LL_IP6_MULTICAST_ADDR_0, LL_IP6_MULTICAST_ADDR_1};
  
  *(uint32_t *)(addr + 2) = group->addr[3];
  if (action == NETIF_ADD_MAC_FILTER)
    printf("Join group %s! bss=0x%02x\n", ip6addr_ntoa(group), ethernetif->bss);
  else if (action == NETIF_DEL_MAC_FILTER)
    printf("Leave group %s! bss=0x%02x\n", ip6addr_ntoa(group), ethernetif->bss);
  else
    return ERR_ARG;
  
  if (ethernetif->bss == BSS_STA)
  {
    if (action == NETIF_ADD_MAC_FILTER)
      ret = WiFi_JoinMulticastGroup(addr);
    else if (action == NETIF_DEL_MAC_FILTER)
      ret = WiFi_LeaveMulticastGroup(addr);
    
    if (ret == -1)
      return ERR_IF;
    
    return ERR_OK;
  }
  else if (ethernetif->bss == BSS_UAP)
    return ERR_OK;
  else
    return ERR_ARG;
}
#endif

#endif /* 0 */
